FROM node:18.7.0-alpine

WORKDIR /app
RUN chown -R node:node /app
ENV PATH /app/node_modules/.bin:$PATH

COPY --chown=node:node package.json ./
COPY --chown=node:node yarn.lock ./

RUN yarn install --frozen-lockfile

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY --chown=node:node . ./

USER node
CMD ["yarn", "dev"]
